services:
  app:
    image: ghcr.io/floerio/ofl-running-analysis:latest
    container_name: ofl-running-analysis
    restart: unless-stopped
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.ofl-running-analysis.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.ofl-running-analysis.entrypoints=websecure"
      - "traefik.http.routers.ofl-running-analysis.tls.certresolver=letsencrypt"
      - "traefik.http.services.ofl-running-analysis.loadbalancer.server.port=8501"
    networks:
      - proxy

networks:
  proxy:
    external: true
